### ISSUE TITLE
[OLD] Legacy Turkish Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/tr.react.dev#1]
## Çeviri Yapmadan Önce Lütfen Aşağıdaki Kuralları Okuyunuz

Çeviri yapma süreci üç adımda gerçekleştirilir: 
1. Kontrol listesinde kimsenin işaretlemediği bölümleri seçiniz. Altındaki yorumları kontrol ederek emin olunuz. İpucu: `CTRL+F` ile istediğiniz bölümle ilgili arama yaparak kontrol edebilirsiniz.

2. Hangi sayfayı çevireceğinizi yorum kısmına yazınız. **Lütfen bir seferde birden fazla sayfa almayınız!** 

3. Projeyi yerel makinenize clone'layınız. Sayfayı çevirdiğinizde commit ederek, pull request gönderiniz. 

4. Commit mesajlarini ingilizce yaziniz.

5. Commit mesajlarinda gecmis zaman formu kullanmayiniz. `translated tutorial page` yerine **`translate tutorial page`**. ya da `fixed a typo in docs` yerine **`fix a typo in docs`**. 

**Tercüme etmeden önce, [çeviri kurallarını](https://github.com/reactjs/tr.reactjs.org/blob/master/TRANSLATION.md) mutlaka okuyunuz.**

İlgili tartışmalara dahil olmak için [Slack #tr](https://rt-slack-invite.herokuapp.com/) kanalına katılın.

## Maintainer List

* @alioguzhan
* @yunusemredilber 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [x] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@helloanil) #2
* [x] Tutorial (@ozcanzaferayan) #3 

### Basics

* [x] Hello World (@enesTufekci) #8
* [x] Introducing JSX (@ozcanzaferayan) #65 
* [x] Rendering Elements (@ozcanzaferayan) #12 
* [x] Components and Props (@ozcanzaferayan) #14
* [x] State and Lifecycle (@ozcanzaferayan) #15
* [x] Handling Events (@ozcanzaferayan) #29 
* [x] Conditional Rendering (@alperen)
* [x] Lists and Keys (@alioguzhan) #22 
* [x] Forms (@aykutkardas) #16
* [x] Lifting State Up (@Poseid10ur) #19
* [x] Composition vs Inheritance (@omergulcicek) #51 
* [x] Thinking in React (@alioguzhan) #34 

### API Reference

* [x] React (@ahmett) #70 
* [x] React.Component() (@ozcanzaferayan) #32 
* [x] ReactDOM (@ekocibar ) #40 
* [x] ReactDOMServer (@alioguzhan) #67 
* [x] DOM Elements (@Poseid10ur) #28
* [x] SyntheticEvent (@helloanil) #36 
* [x] Test Utilities (@Poseid10ur) #37 
* [x] Shallow Renderer (@suyalcinkaya) #71 
* [x] Test Renderer (@erinc35) #42 
* [x] JS Environment Requirements (@ebrugulec) #41 
* [x] Glossary (@suyalcinkaya) #53 

### Navigation

These are the navigation links that appear in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml (@theilgazcode) #60 
* [x] docs/nav.yml (@alperen) #86 

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started (@mahmutkaya) #26
* [x] Add React to a Website (@mahmutkaya) #26
* [x] Create a New React App (@mertcb) (@mertoguz)  #63 
* [x] CDN Links (@mahmutkaya) #26
* [x] Release Channels `content/docs/release-channels.md` (@eminaydin) #211 

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks (@suyalcinkaya) #93 
  * [x] Hooks at a Glance (@hbarang) #161
  * [x] Using the State Hook (@hakanbakacak) #107 
  * [x] Using the Effect Hook (@EngincanV) #245 
  * [x] Rules of Hooks (@suyalcinkaya) (#54)
  * [x] Building Your Own Hooks (@ozcanzaferayan) (#91)
  * [x] Hooks API Reference (@sametweb) (#266) 
  * [ ] Hooks FAQ 

### Concurrent Mode (New)

- [x] Adopting Concurrent Mode `content/docs/concurrent-mode-adoption.md` (@aakay) (#202)
- [x] Introducing Concurrent Mode `content/docs/concurrent-mode-intro.md` (@ataberkgrl ) (#253)
- [ ] Concurrent UI Patterns `content/docs/concurrent-mode-patterns.md`
- [x] Concurrent Mode API Reference `content/docs/concurrent-mode-reference.md` (@ahmett) (#210)
- [ ] Suspense for Data Fetching `content/docs/concurrent-mode-suspense.md`

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [x] dont-call-proptypes (@muratdogan17) #84 
* [x] invalid-aria-prop (@suyalcinkaya) (#55)
* [x] invalid-hook-call-warning (@emrekara37) #144 
* [x] legacy-factories (@muratdogan17) #85 
* [x] refs-must-have-owner (@muratdogan17) #89 
* [x] special-props (@suyalcinkaya) (#56)
* [x] unknown-prop (@alioguzhan) ) (#295)

### Advanced Guides

* [x] Accessibility (@fatmabadri) #279 
* [x] Code-Splitting (@mustaphaturhan) #44 
* [x] Context (@metinsut) #108 
* [x] Error Boundaries (@aakay) #109 
* [x] Forwarding Refs (@ngTurk) #222
* [x] Fragments (@ebrugulec) #81
* [x] Higher-Order Components (@hbarang) #159 
* [x] Integrating with Other Libraries (@fatmabadri) #272 
* [x] JSX In Depth (@yunusemredilber) #212 
* [ ] Optimizing Performance
* [x] Portals #98 (@ahmett)
* [x] React Without ES6 (@mustaphaturhan) #48 
* [x] React Without JSX (@ahmett) #47 
* [x] Reconciliation (@yunusemredilber) #207 
* [x] Refs and the DOM (@SafaElmali) #83 
* [x] Render Props (@hbarang) #153 
* [x] Static Type Checking (@aakay) #105 
* [x] Strict Mode (@metinogurlu) #209 
* [x] Typechecking With PropTypes (@ahmett) (#50)
* [x] Uncontrolled Components (@ahmett) (#66)
* [x] Web Components (@suyalcinkaya) (#59)

### FAQ

* [x] AJAX and APIs (@emreyalvac) #18 
* [x] Babel, JSX, and Build Steps (@suyalcinkaya) (#68)
* [x] Passing Functions to Components (@umutcanbolat) #111 
* [x] Component State (@suyalcinkaya) #94 
* [x] Styling and CSS (@yunusemredilber) #208 
* [x] File Structure  (@umutcanbolat) #99 
* [x] Versioning Policy (@Oedipus) #103 
* [x] Virtual DOM and Internals (@suyalcinkaya) #97 

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [x] CodeEditor (@alioguzhan) #78
* [x] CodeExample (@alioguzhan) #77
* [x] ErrorDecoder (@alioguzhan) #79
* [x] LayoutFooter (@alioguzhan) #73 
* [x] LayoutHeader (@alioguzhan) #73 
* [x] MarkdownPage (@alioguzhan) #76

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [x] Community (@reincore) #123

**Comment by ozcanzaferayan** [comment]
I can take Tutorial page.

**Comment by helloanil** [comment]
- [ ] Home Page @helloanil

**Comment by enesTufekci** [comment]
- [ ] Hello World @enesTufekci

**Comment by tesseralis** [comment]
You all should be able to edit the issue itself by clicking the edit button:

<img width="801" alt="screen shot 2019-02-15 at 12 21 09 pm" src="https://user-images.githubusercontent.com/1278991/52882342-389a6a80-311c-11e9-9b15-401f2bf27887.png">

**Comment by alperen** [comment]
- [ ] Conditional Rendering @alperen

**Comment by alioguzhan** [comment]
- [ ] Lists and Keys @alioguzhan

**Comment by ozcanzaferayan** [comment]
@alperen @alioguzhan, bu issue'yü yukarıdan editleyip ilgili alanları kendinize atayabilirsiniz. 
Örnek: (@alioguzhan) şeklinde. 
Ayrıca aşağıdaki linkten Slack ReactJS #tr kanalına girebilirsiniz. 
https://rt-slack-invite.herokuapp.com/

**Comment by alperen** [comment]
Merhaba ben issue'yu editleyemiyorum.

**Comment by sinasen2000** [comment]
Merhabalar,

Ben Sina, Hollanda Delft Teknoloji Üniversitesi'nde 1. yıl Computer Science öğrencisiyim. Birinci alanım Java olmasına ve JS ve React'e yeteri kadar hakim olmamama rağmen, bu projeye katkıda bulunmak istiyorum yavaş yavaş da olsa. Daha önce KhanAcademy'de de çevirmenlik geçmişim var. Acaba ben de bu projeye katkıda bulunabilir miyim?

Saygılarımla,
Sina Şen

________________________________
Gönderen: Özcan Zafer AYAN <notifications@github.com>
Gönderildi: 24 Şubat 2019 Pazar 08:54
Kime: reactjs/tr.reactjs.org
Bilgi: sinasen2000; Manual
Konu: Re: [reactjs/tr.reactjs.org] Turkish Translation Progress (#1)


@alperen<https://github.com/alperen> @alioguzhan<https://github.com/alioguzhan>, bu issue'yü yukarıdan editleyip ilgili alanları kendinize atayabilirsiniz.
Örnek: (@alioguzhan<https://github.com/alioguzhan>) şeklinde.
Ayrıca aşağıdaki linkten Slack ReactJS #tr kanalına girebilirsiniz.
https://rt-slack-invite.herokuapp.com/

**Comment by ozcanzaferayan** [comment]
@sinasen2000 kalanlardan issue'lardan istediğini seçip başlayabilirsin.

**Comment by Poseid10ur** [comment]
> * [ ] Lifting state up @Poseid10ur

**Comment by omergulcicek** [comment]
- [ ] Composition vs Inheritance @omergulcicek

**Comment by tahaygun** [comment]
API Reference - React @tahaygun

**Comment by mahmutkaya** [comment]
Installation - Getting Started  @mahmutkaya

**Comment by pesh12** [comment]
API Reference - ReactDOM @pesh12

**Comment by arasmr** [comment]
Api Reference - ReactDomServer @arasmr

**Comment by mahmutkaya** [comment]
- [ ]  Installation - Add React to a Website @mahmutkaya

**Comment by sinasen2000** [comment]
Styling and CSS @sinasen2000

**Comment by sinasen2000** [comment]
Styling and CSS - sinasen2000

**Comment by Poseid10ur** [comment]
> * [ ]  DOM Elements @Poseid10ur

**Comment by helloanil** [comment]
[ ] Hooks FAQ @helloanil

**Comment by suyalcinkaya** [comment]
- [ ] Core Pages > API Reference > Glossary @suyalcinkaya

**Comment by Poseid10ur** [comment]
> * [ ] Test Utilities @Poseid10ur

**Comment by mertcb** [comment]
- [ ]  Create a New React App @mertcb

**Comment by mahmutkaya** [comment]
- [ ]  CDN Links @mahmutkaya

**Comment by ozcanzaferayan** [comment]
Arkadaşlar merhaba, 

Çeviri kuralları gereği bir çeviriyi bitirmeden diğerine geçmeyiniz. Lütfen sadece tek bir konu belirleyip 2 gün içerisinde geri dönüş yapar mısınız?

@mahmutkaya 
@alioguzhan 
@enesTufekci 

Teşekkürler,

**Comment by mahmutkaya** [comment]
Merhaba @ozcanzaferyan

Şu an bitmemiş bi çeviri yok bende ama son yaptığım pr gözüküyor mu acaba?
Son pr.de ilk aldığım sayfada da küçük bir değişiklik yapıp iki sayfayı birden push etmiştim :) bundan dolayı mı bi sıkıntı oldu  🤔

**Comment by ozcanzaferayan** [comment]
Listede bitmemiş göründüğü için belirttim. PR'ını review ettim. Eline sağlık güzel olmuş. Çevirilerde kendi yorumlarını uygun biçimde katabilirsin. Bunun hakkında örnekler ekledim. Teşekkürler, kolay gelsin.

**Comment by erinc35** [comment]
Introducing Hooks u cevirmek istiyorum.

**Comment by Poseid10ur** [comment]
@ozcanzaferayan & @erinc35  selamlar,

Önceki yorumlarda Test Utilities dökümanının çevirmek için yorum atmıştım, az önce onunla ilgili PR açtım. Çevrilmemiş diğer dökümanlara bakmak için listeyi incelediğimde şu an @erinc35 de Test Utilities üzerinde çalışıyor görünüyor :) Nasıl yapalım?

**Comment by helloanil** [comment]
- [ ] Shallow Renderer @helloanil

**Comment by ozcanzaferayan** [comment]
> @ozcanzaferayan & @erinc35 selamlar,
> 
> Önceki yorumlarda Test Utilities dökümanını çevirmek için yorum atmıştım, az önce onunla ilgili PR açtım. Çevrilmemiş diğer dökümanlara bakmak için listeyi incelediğimde şu an @erinc35 de Test Utilities üzerinde çalışıyor görünüyor :) Nasıl yapalım?

Pardon, hözümden kaçmış. Güncelliyorum.

**Comment by ebrugulec** [comment]
- [ ] JS Environment Requirements

**Comment by muratdogan17** [comment]
- [ ] dont-call-proptypes @muratdogan17

**Comment by ebrugulec** [comment]
- [ ] Fragments

**Comment by theilgazcode** [comment]
* [ ]  Introducing Hooks @theilgazcode

**Comment by theilgazcode** [comment]
*[ ] tutorial/nav.yml @theilgazcode

**Comment by theilgazcode** [comment]
> * [ ]  tutorial/nav.yml @theilgazcode

**Comment by alperen** [comment]
- [ ] docs/nav.yml @alperen

**Comment by mustaphaturhan** [comment]
- [ ]  Code-Splitting @mustaphaturhan

**Comment by ahmedkaba** [comment]
- [ ] React Without JSX @ahmedkaba

**Comment by theilgazcode** [comment]
* [ ] JSX In Depth @theilgazcode

**Comment by hakanbakacak** [comment]
Using the State Hook @hakanbakacak

**Comment by mustaphaturhan** [comment]
- [ ] React Without ES6 @mustaphaturhan

**Comment by ahmedkaba** [comment]
- [ ] Typechecking With PropTypes @ahmedkaba

**Comment by ahmedkaba** [comment]
- [ ] Uncontrolled Components @ahmedkaba

**Comment by ozcanzaferayan** [comment]
Merhaba,

Öncelikle çevirilerde ve incelemelerde katkıda bulunan herkese çok teşekkürler. Sayenizde Core Pages kısmı %70'e ulaştı, %100'e 6 adet yazı kaldı. Bitmek üzere olan 4 dil arasındayız.

Core pages kısmında işleri kalan arkadaşlar bu mesaja geri dönüş yapabilirler mi? Buna göre 6 sayfa için ilgili atamalar tekrar yapılandırılacaktır.

(@enesTufekci, @omergulcicek, @tahaygun, @arasmr, @helloanil, @suyalcinkaya)

Teşekkürler,

**Comment by omergulcicek** [comment]
Tamamladım, merge edildi :+1: 

> Merhaba,
> 
> Öncelikle çevirilerde ve incelemelerde katkıda bulunan herkese çok teşekkürler. Sayenizde Core Pages kısmı %70'e ulaştı, %100'e 6 adet yazı kaldı. Bitmek üzere olan 4 dil arasındayız.
> 
> Core pages kısmında işleri kalan arkadaşlar bu mesaja geri dönüş yapabilirler mi? Buna göre 6 sayfa için ilgili atamalar tekrar yapılandırılacaktır.
> 
> (@enesTufekci, @omergulcicek, @tahaygun, @arasmr, @helloanil, @suyalcinkaya)
> 
> Teşekkürler,

**Comment by ozcanzaferayan** [comment]
Core Pages'taki tamamlanmayan iş atamaları kaldırıldı.

**Comment by ozcanzaferayan** [comment]
Introducing JSX @ozcanzaferayan

**Comment by ahmedkaba** [comment]
- [ ] API Reference > React @ahmedkaba

**Comment by metinsut** [comment]
- [ ] Context @metinsut

**Comment by SafaElmali** [comment]
I would like to translate Advanced Guides > Refs and the DOM @safaelmali

**Comment by muratdogan17** [comment]
legacy-factories @muratdogan17

**Comment by alioguzhan** [comment]
Hey @alperen , the last section in core pages is just completed. We are good to go. Now we can translate `docs/nav.yml` and release it. Waiting to hear from you.

And thanks to everyone that contributed to this project. It was a great process.

**Comment by alperen** [comment]
I made a lot of changes on `docs/nav.yml` already. Today, i'm going to do last changes and reviews. I will inform you. @alioguzhan

**Comment by ahmedkaba** [comment]
- [ ] Advanced Guides > Portals @ahmedkaba

**Comment by etakgoz** [comment]
Advanced Guides > Accessibility @etakgoz

**Comment by muratdogan17** [comment]
refs-must-have-owner @muratdogan17

**Comment by alperen** [comment]
New page added to our repository  with commit `e744030`. Please add `content/docs/reference-glossary.md` file to task list.

**Comment by alioguzhan** [comment]
> New page added to our repository with commit `e744030`. Please add `content/docs/reference-glossary.md` file to task list.

Not really. We already had that file. It was just an update with some conflicts. I fixed them. Thanks.

**Comment by muratdogan17** [comment]
unknown-prop @muratdogan17

**Comment by umutcanbolat** [comment]
Hi, I would like to translate FAQ > File Structure @umutcanbolat

**Comment by ozcanzaferayan** [comment]
Building Your Own Hooks @ozcanzaferayan

**Comment by umutcanbolat** [comment]
FAQ > Passing Functions to Components @umutcanbolat

**Comment by Oedipus** [comment]
Versioning Policy @Oedipus

**Comment by serkankayaa** [comment]
ADVANCED GUIDES > Reconciliation  @serkankayaa

**Comment by ozcanzaferayan** [comment]
Using the Effect Hook @ozcanzaferayan

**Comment by ahmedkaba** [comment]
- [ ] Hooks > Hooks API Reference @ahmedkaba

**Comment by aakay** [comment]
Static Type Checking @aakay

**Comment by Oedipus** [comment]
invalid-hook-call-warning @oedipus

**Comment by aakay** [comment]
error-boundaries @aakay

**Comment by alioguzhan** [comment]
> invalid-hook-call-warning @Oedipus
> 
> I won't be able to finish due to other commitments. Sorry for the inconvenience. cc: @alioguzhan

No worries. Thanks for letting me know!

**Comment by reincore** [comment]
Hi, I would like to start translating with the Community -> Support page.

**Comment by alioguzhan** [comment]
> Hi, I would like to start translating with the Community -> Support page.

Thanks. There are really short and small pages to translate in the Community section. Is it OK to assign the whole section to you? Actually, It should be fine if we translate only `Support`, `Courses` and `Examples` sections. Rest can be omitted for now.

**Comment by reincore** [comment]
For sure, I'd be happy to help.

**Comment by hamdiceylan** [comment]
- [ ] Hooks > Hooks FAQ @hamdiceylan

**Comment by emrekara37** [comment]
Optimizing Performance **@emrekara37**

**Comment by mehmetkose** [comment]
Design Principles @mehmetkose

**Comment by hbarang** [comment]
Render Props @hbarang

**Comment by hbarang** [comment]
Higher-Order Components @hbarang

**Comment by alioguzhan** [comment]
I am removing assignments from the items that have no activities or updates for a while. 

@mehmetkose 
@theilgazcode 
@hamdiceylan 
@ahmedkaba 
@sinasen2000 
@etakgoz
@muratdogan17 
@serkankayaa

**Comment by hbarang** [comment]
Hooks at a Glance @hbarang

**Comment by hbarang** [comment]
unknown-prop @hbarang

**Comment by alioguzhan** [comment]
I am removing the assignments from the items that have no activities or updates for a while.

@ozcanzaferayan 
@suyalcinkaya

**Comment by aakay** [comment]
Adopting Concurrent Mode @aakay

**Comment by yunusemredilber** [comment]
Advanced Guides > Reconciliation @yunusemredilber

**Comment by yunusemredilber** [comment]
FAQ > Styling and CSS @yunusemredilber

**Comment by yunusemredilber** [comment]
Advanced Guides > JSX In Depth @yunusemredilber

**Comment by metinogurlu** [comment]
Advanced Guides > Strict Mode

**Comment by ahmett** [comment]
- [ ] Concurrent Mode API Reference @ahmett

By the way, @alioguzhan can you replace my old usernames on the list with new ones? Thanks already.

**Comment by alioguzhan** [comment]
> * [ ]  Concurrent Mode API Reference @ahmett
> 
> By the way, @alioguzhan can you replace my old usernames on the list with new ones? Thanks already.
> 
> #47 #50 #66 #70 #98

It should be done. Can you verify it, please? @ahmett

**Comment by ahmett** [comment]
> > * [ ]   Concurrent Mode API Reference @ahmett
> > 
> > By the way, @alioguzhan can you replace my old usernames on the list with new ones? Thanks already.
> > #47 #50 #66 #70 #98
> 
> It should be done. Can you verify it, please? @ahmett

All occurrences gone, I appreciate it. 🙏 @alioguzhan

**Comment by eminaydin** [comment]
Release Channels > @eminaydin

**Comment by ngTurk** [comment]
Advanced Guides > Forwarding Refs > @ngTurk

**Comment by ngTurk** [comment]
@alioguzhan @yunusemredilber could you please grant me access on the repo, please.

**Comment by aakay** [comment]
@ngTurk have you tried forking and creating a pr?

**Comment by alioguzhan** [comment]
> @alioguzhan @yunusemredilber could you please grant me access on the repo, please.

If this for the translation you can fork the repo and create a PR, as @aakay suggested.

**Comment by ataberkgrl** [comment]
- [ ] Introducing Concurrent Mode @ataberkgrl

**Comment by fatmabadri** [comment]
Integrating with Other Libraries @fatmabadri

**Comment by fatmabadri** [comment]
:heavy_check_mark:<a href="https://github.com/reactjs/tr.reactjs.org/blob/master/content/docs/accessibility.md">Accessibilty</a> @fatmabadri

**Comment by fatmabadri** [comment]
> ✔️[Accessibilty](https://github.com/reactjs/tr.reactjs.org/blob/master/content/docs/accessibility.md) @fatmabadri

Hi @alioguzhan, I just kindly remind you, you have a DM about translations on Slack.

**Comment by xeptao** [comment]
- [x] LayoutFooter (@xeptao)

**Comment by umtdemr** [comment]
- [ ] Beta docs - Start a new react project.

**Comment by gaearon** [comment]
Thanks to everyone who contributed to the old website translation!
Started a new issue for the new website: https://github.com/reactjs/tr.react.dev/issues/397
